"use client";

import { useCallback, useEffect, useRef, useState } from "react";

const W=250,H=300;
type Pt={x:number;y:number}; type Shot=Pt&{vx:number;vy:number};
type Enemy=Pt&{kind:number;phase:number;sprite:HTMLImageElement};
const hit=(a:Pt,b:Pt,r=15)=>Math.abs(a.x-b.x)<r&&Math.abs(a.y-b.y)<r;

export default function Home(){
 const canvasRef=useRef<HTMLCanvasElement>(null), keys=useRef(new Set<string>()), images=useRef<Record<string,HTMLImageElement>>({});
 const game=useRef({running:false,paused:false,alive:true,player:{x:105,y:245},shots:[] as Pt[],enemyShots:[] as Shot[],enemies:[] as Enemy[],score:0,hi:0,bombs:1,chain:0,wave:0,spawn:40,blast:null as null|{x:number;y:number;r:number}});
 const [status,setStatus]=useState("READY");
 const reset=useCallback(()=>{const g=game.current;Object.assign(g,{running:true,paused:false,alive:true,player:{x:105,y:245},shots:[],enemyShots:[],enemies:[],score:0,bombs:1,chain:0,wave:0,spawn:35,blast:null});setStatus("PLAYING");canvasRef.current?.focus()},[]);
 const fire=useCallback(()=>{const g=game.current;if(g.running&&g.alive&&!g.paused&&g.shots.length<3)g.shots.push({x:g.player.x+8,y:g.player.y-7})},[]);
 const bomb=useCallback(()=>{const g=game.current;if(g.running&&g.alive&&!g.paused&&g.bombs>0&&!g.blast){g.bombs--;g.blast={x:g.player.x+8,y:g.player.y+8,r:10}}},[]);
 useEffect(()=>{["solv","zap","fel","melanza","espa","cube"].forEach(n=>{const i=new Image();i.src=`/sprites/${n}.gif`;images.current[n]=i});game.current.hi=Number(localStorage.getItem("xevious-hi")||0)},[]);
 useEffect(()=>{const down=(e:KeyboardEvent)=>{const k=e.key.toLowerCase();if(["arrowup","arrowdown","arrowleft","arrowright","x","c","p"," "].includes(k))e.preventDefault();keys.current.add(k);if(k==="x"||k===" ")fire();if(k==="c")bomb();if(k==="p"&&game.current.running){game.current.paused=!game.current.paused;setStatus(game.current.paused?"PAUSED":"PLAYING")}if(k==="r")reset()};const up=(e:KeyboardEvent)=>keys.current.delete(e.key.toLowerCase());window.addEventListener("keydown",down,{passive:false});window.addEventListener("keyup",up);return()=>{window.removeEventListener("keydown",down);window.removeEventListener("keyup",up)}},[bomb,fire,reset]);
 useEffect(()=>{const canvas=canvasRef.current;if(!canvas)return;const ctx=canvas.getContext("2d")!;ctx.imageSmoothingEnabled=false;let raf=0,then=performance.now(),acc=0;
  const shootAt=(e:Enemy,t:Pt,spread=0)=>{const a=Math.atan2(t.y-e.y,t.x-e.x)+spread;game.current.enemyShots.push({x:e.x+7,y:e.y+7,vx:Math.cos(a)*1.5,vy:Math.sin(a)*1.5})};
  const tick=()=>{const g=game.current;if(!g.running||g.paused||!g.alive)return;const s=2;if(keys.current.has("arrowleft"))g.player.x-=s;if(keys.current.has("arrowright"))g.player.x+=s;if(keys.current.has("arrowup"))g.player.y-=s;if(keys.current.has("arrowdown"))g.player.y+=s;g.player.x=Math.max(0,Math.min(W-20,g.player.x));g.player.y=Math.max(28,Math.min(H-22,g.player.y));g.shots.forEach(q=>q.y-=7);g.shots=g.shots.filter(q=>q.y>-12);g.spawn--;
   if(g.spawn<=0&&g.enemies.length<5){const level=Math.min(4,1+Math.floor(g.wave/8)),kind=g.wave%12===11?20:g.wave%3+1,name=kind===20?"cube":kind===1?"fel":kind===2?"melanza":"espa";g.enemies.push({x:Math.random()*225,y:-20,kind,phase:0,sprite:images.current[name]});g.wave++;g.spawn=Math.max(14,45-level*6)}
   for(const e of g.enemies){const level=Math.min(5,1+Math.floor(g.wave/10));if(e.kind===20){e.x+=Math.sign(g.player.x-e.x)*.7;e.y+=1}else if(e.kind===2&&e.y>g.player.y-5&&e.phase===0){e.phase=g.player.x<e.x?-1:1;e.x+=e.phase*level}else{e.y+=.8+level*.32;if(e.kind===3&&e.y>75)e.x+=Math.sign(105-e.x)*.65}if(!e.phase&&e.y>70+Math.random()*80&&Math.random()<.018*level){e.phase=1;shootAt(e,g.player);if(level>3)shootAt(e,g.player,.22)}}
   for(let si=g.shots.length-1;si>=0;si--)for(let ei=g.enemies.length-1;ei>=0;ei--)if(hit(g.shots[si],g.enemies[ei],18)){g.shots.splice(si,1);g.enemies.splice(ei,1);g.score+=10;g.chain++;if(g.chain===5){g.bombs++;g.chain=0}break}
   g.enemyShots.forEach(q=>{q.x+=q.vx;q.y+=q.vy});g.enemyShots=g.enemyShots.filter(q=>q.x>-8&&q.x<W+8&&q.y>-8&&q.y<H+8);
   if(g.blast){g.blast.r+=7;g.enemies=g.enemies.filter(e=>{const safe=Math.hypot(e.x-g.blast!.x,e.y-g.blast!.y)>g.blast!.r;if(!safe)g.score+=10;return safe});g.enemyShots=g.enemyShots.filter(q=>Math.hypot(q.x-g.blast!.x,q.y-g.blast!.y)>g.blast!.r);if(g.blast.r>380)g.blast=null}
   if(g.enemies.some(e=>hit(g.player,e,18))||g.enemyShots.some(q=>hit(g.player,q,12))){g.alive=false;g.hi=Math.max(g.hi,g.score);localStorage.setItem("xevious-hi",String(g.hi));setStatus("GAME OVER")}g.enemies=g.enemies.filter(e=>e.y<H+25&&e.x>-30&&e.x<W+30)};
  const draw=()=>{const g=game.current;ctx.fillStyle="#020806";ctx.fillRect(0,0,W,H);ctx.fillStyle="#10352a";for(let y=25;y<H;y+=24){const yy=(y+performance.now()/45)%H;ctx.fillRect(18,yy,1,1);ctx.fillRect(219,(yy+11)%H,1,1)}ctx.font="10px monospace";ctx.fillStyle="#f4f2d8";ctx.fillText(`HI ${String(g.hi).padStart(5,"0")}`,84,13);ctx.fillText(String(g.score).padStart(5,"0"),202,13);if(g.running&&g.alive&&images.current.solv?.complete)ctx.drawImage(images.current.solv,g.player.x,g.player.y);g.shots.forEach(q=>images.current.zap?.complete&&ctx.drawImage(images.current.zap,q.x,q.y));g.enemies.forEach(e=>e.sprite?.complete&&ctx.drawImage(e.sprite,e.x,e.y));ctx.fillStyle="#ffe85c";g.enemyShots.forEach(q=>ctx.fillRect(q.x,q.y,4,4));if(g.blast){ctx.strokeStyle="#ffe85c";ctx.lineWidth=5;ctx.beginPath();ctx.arc(g.blast.x,g.blast.y,g.blast.r,0,Math.PI*2);ctx.stroke()}ctx.fillStyle="#a5ffcf";ctx.fillText(`BOMBS ${g.bombs}`,7,290);ctx.fillText(`CHAIN ${g.chain}/5`,169,290);if(!g.running||!g.alive||g.paused){ctx.fillStyle="rgba(2,8,6,.72)";ctx.fillRect(34,118,182,55);ctx.textAlign="center";ctx.fillStyle="#f4f2d8";ctx.font="bold 13px monospace";ctx.fillText(!g.running?"CLICK TO START":g.paused?"PAUSE":"GAME OVER",W/2,143);ctx.font="9px monospace";ctx.fillStyle="#83ffc0";ctx.fillText(!g.running?"ARROWS / X / C":g.alive?"PRESS P TO RESUME":"CLICK TO RESTART",W/2,160);ctx.textAlign="left"}};
  const loop=(now:number)=>{acc=Math.min(acc+now-then,100);then=now;while(acc>=20){tick();acc-=20}draw();raf=requestAnimationFrame(loop)};raf=requestAnimationFrame(loop);return()=>cancelAnimationFrame(raf)},[]);
 const hold=(k:string,on:boolean)=>{on?keys.current.add(k):keys.current.delete(k);canvasRef.current?.focus()};
 return <main><section className="intro"><p className="eyebrow">REBUILT FROM A STUDENT JAVA APPLET</p><h1>XEVIOUS <span>RE:FLIGHT</span></h1><p className="lede">あの頃の250×300ピクセルを、いまのブラウザへ。<br/>原作の手触りを残した、小さな縦スクロールシューティング。</p><div className="meta"><span>ORIGINAL CODE</span><b>JAVA APPLET</b><span>NOW RUNNING</span><b>HTML5 CANVAS</b></div></section>
 <section className="cabinet" aria-label="シューティングゲーム"><div className="bezel"><div className="screen-label"><span>SYSTEM 01</span><i>{status}</i></div><canvas ref={canvasRef} width={W} height={H} tabIndex={0} onClick={()=>{if(!game.current.running||!game.current.alive)reset()}} aria-label="ゲーム画面。クリックで開始"/><p className="hint">CLICK SCREEN TO START / RESTART</p></div><div className="controls"><div className="dpad" aria-label="移動ボタン"><button className="up" aria-label="上" onPointerDown={()=>hold("arrowup",true)} onPointerUp={()=>hold("arrowup",false)}>▲</button><button className="left" aria-label="左" onPointerDown={()=>hold("arrowleft",true)} onPointerUp={()=>hold("arrowleft",false)}>◀</button><button className="right" aria-label="右" onPointerDown={()=>hold("arrowright",true)} onPointerUp={()=>hold("arrowright",false)}>▶</button><button className="down" aria-label="下" onPointerDown={()=>hold("arrowdown",true)} onPointerUp={()=>hold("arrowdown",false)}>▼</button></div><button className="action bomb" onPointerDown={bomb}><small>C</small>BOMB</button><button className="action shoot" onPointerDown={fire}><small>X</small>SHOT</button></div></section>
 <aside className="manual"><h2>FLIGHT MANUAL</h2><dl><div><dt>MOVE</dt><dd>ARROW KEYS</dd></div><div><dt>SHOT</dt><dd>X / SPACE</dd></div><div><dt>BOMB</dt><dd>C</dd></div><div><dt>PAUSE</dt><dd>P</dd></div><div><dt>RESTART</dt><dd>R</dd></div></dl><p>敵を5機連続で撃墜するとボムを補給。ウェーブが進むほど敵は速く、攻撃は激しくなる。</p></aside><footer>AN ARCHIVE RESTORED FOR THE MODERN WEB <span>© ORIGINAL CREATOR</span></footer></main>
}
